apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lwwebapp1
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    directory:
      recurse: true
    repoURL: https://github.com/santoshnog/argocd_training_2024_code.git
    path: prod
    targetRevision: main


